services:
  server:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./public
        target: /app/public
    restart: always
volumes:
  public:
